version: "3.8"

services:
  db:
    image: postgres:13
    container_name: living_chat_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-strong-db-password
      POSTGRES_DB: living_chat_bot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod
    container_name: living_chat_bot
    restart: always
    env_file:
      - ../.env.prod
    depends_on:
      - db

volumes:
  db_data:
